#!/bin/sh

set -eux

cd "$(dirname "$0")"/..

for cli in pgcli mycli litecli mssql-cli iredis; do
  echo \"$cli\" \
  | npx mustache - Dockerfile.template \
  | docker build - -t testcab/$cli --pull
done
