#!/bin/sh

set -eux

for cli in pgcli mycli litecli mssql-cli iredis; do
  version=$(docker run --rm -it testcab/$cli --version | grep -Po '[\d.]+')
  docker tag testcab/$cli testcab/$cli:$version
  docker push testcab/$cli
  docker push testcab/$cli:$version
done
